### ISSUE TITLE
Low Frame Rate

### ISSUE THREAD

**Issue by J0RMUNG4NDR** [TillRauch/GameOfLife#1]
Frame rate starts already low. The longer the "simulation" is running, the lower the frame rate becomes. Renders the window unresponsive between updates.

**Comment by TillRauch** [comment]
Turns out the used visualisation-library `tkinter` keeps track of all created rectangles.
In the next version rectangles will be removed before new ones are added.

**Comment by TillRauch** [comment]
fixed by f19afcc8d87ba024495a348e4124fabba8d1031b
